### ISSUE TITLE
Russian WordNet

### ISSUE THREAD

**Issue by djbpitt** [mtm80/russ-project#35]
It may not be practical to explore YARN (<https://russianword.net/>) within our short, one-semester framework, but it’s an open-source Russian version of <https://wordnet.princeton.edu/>, and might be useful for machine-assisted semantic exploration of Russian texts.

**Comment by richiebful** [comment]
I definitely want to use this in a future project, but I think we have enough going on, with two months remaining, between lemmatizing, topic modeling, and Ian's system of manual marking. Seems like a really useful resource.
