### ISSUE TITLE
Project Update: 30-01-2018

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#4]
**This past week**
We held an organizational meeting with @zme1 to help us get the project started.
**This next week**
We want to accomplish the following in this next week:
- Look into available campaign transcripts (speeches, interviews, etc), put URLs in [sources.md](https://github.com/mtm80/russ-project/blob/master/sources.md)
- Based on source availability and our interest, narrow the research question
- Discuss an initial handful of features that we want to analyze to answer our research question
- Read up on [TEI](http://www.tei-c.org/index.xml), then vote on whether to use or not

**Comment by JosephDRogers23** [comment]
Our project is in a similar position to yours, and it's cool to see how you guys are handling gathering sources as well. We have a simple text file to compile our sources with brief descriptions and titles/authors added below, but I feel that using a markdown file is much more useful and will make it easier to come back to the listing in the future if we decide to add or drop sources later on in the project cycle.

**Comment by brucknerp** [comment]
Like Joseph mentioned, it's interesting that both of your groups are considering TEI. Our group is having our meeting tomorrow so we will definitely bring it up. Because our project is also on speech, I looked for transcripts of TV or movies, but couldn't find much. I'm glad you all seem to have gotten some good sources to work with. Looking forward to seeing what your more narrow research questions are.

**Comment by Idi0teque** [comment]
Hey! As Joseph mentioned, we're also going to be using TEI. If you do decide to use it, I personally would love to share notes on if you got it working or not, and how precisely to do so!

**Comment by danakaufhold** [comment]
I think this is such a cool project idea, and I'll be really interested to see what documents you guys pick to look at. I'm super into American politics, so looking at the Russian side of things will be eye-opening, especially when it comes to things like a candidate's rhetoric, or "voice." I'll definitely keep watching to see what all you choose, and what conclusions you're able to draw.

**Comment by djbpitt** [comment]
With respect to US political discourse, some of you already know that Zac’s project, when he was an enrolled student in this course a year ago, involved a critical discourse analysis of presidential candidate speech about immigration. The project site is at http://immigration.obdurodon.org/ and the repo is at https://github.com/ech45/immigration_station. This semester’s exploration of Russian political speech seems to draw on some of the same methods.
