### ISSUE TITLE
Project issue 12 March 

### ISSUE THREAD

**Issue by mtm80** [mtm80/russ-project#52]
Since to meeting prior to spring break, Ian has created most of the html and css that will be used on our site with some finishing touches remaining.  He plans to finish compiling the remaining Grudinin texts.  Richard finished running  mystem on our docs and plans to work on the website with Ian.
Matt wrote a portion of the Homepage and an about page with further expansion to come pending suggestions from other team members.  Also, he plans to associate the Zhirinovsky texts with the schema.

**Comment by rmb165** [comment]
It's great that this group is moving so quickly on the website! Are multiple people working on the XML? With my group's magic realist texts, I found it difficult that we had two people mark up texts and another person create the schema. How are you navigating the process of finishing the xml markup and associating them with the schema?

**Comment by brucknerp** [comment]
I know I will see it as soon as the site goes up, but how did you decide on your site layout/css designing? Is there a theme or motif?

**Comment by Idi0teque** [comment]
How has Mystem worked out? Was it more work than it was worth or do you guys think it ended up being useful? Same with TEI, though I guess that's less "more work" and more "different work"...
