### ISSUE TITLE
Read and summarize "Fleeing, Sneaking, Flooding"

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#6]
Found in file "Corpus_linguistics[2].pdf" in email

**Comment by mtm80** [comment]
The basic premise of the article is the analysis of refugees/migrants in the British press and politics.  In the introduction, it is stated that "critical discourse analysis" has been the typical method of analysis.  This only uses a small sample of texts for analysis while another option is "corpus-based"  which analyzes a large range of text sources.  The former focuses on positive/negative representations of the self or others, argumentation, and linguistic analysis.  The latter would be impractical for our project as it would be too large in scope.  Data was searched and collected predictably through the use of key terms and from a range of UK newspapers and tabloids.  Particular words of note in the methodology were keyness, collocation, semantic preference, and semantic/discourse prosody.  As these are technical terms, I will not define them here for the sake of brevity.  By my estimation, these are probably not relevant for our purposes as our sample sizes are relatively small though Ian my want to have a look at them for the sake of his linguistic interest.

**Comment by richiebful** [comment]
@mtm80 If you could just move this analysis to ```/research/``` as a .md file, that'd be great
