### ISSUE TITLE
Project Update 21 March

### ISSUE THREAD

**Issue by mtm80** [mtm80/russ-project#62]
Since the previous week, Ian expanded on the webpage design.  He plans the have the page online, do the markup on the Grudinin texts over the next week, and incorporate web content.  Richie completed the MALLET run and inserted word-level analysis into the TEI structural markup.  He plans to edit the TEI output for punctuation, tweak MALLET, markup the Putin texts with rhetorical tags, and update the Grudinin and Zhirinovsky TEI with word-level data.  Matt marked up the Zhirinovsky texts with structural tags, and wrote web content for the home and about pages.  He plans to markup Zhirinovsky texts with rhetorical tags and expand the web content with greater detail.  

(Richie's edit) Richie's also working on a basic reading view for our documents

**Comment by richiebful** [comment]
Punctuation is now preserved in the output of Mystem (our lemmatizer). Somehow I completely missed that there's a command-line switch for Mystem that retains it (```-c```). I didn't understand the sentiment in "Copy entire input to output."
 
I used the command:
```mystem -c --weight --format xml [infile] [outfile]``` to run it

**Comment by djbpitt** [comment]
@richiebful Concerning the Mystem command-line switch to retain punctuation: As a great American philosopher once said: <https://www.youtube.com/watch?v=cnaeIAEp2pU>

**Comment by brucknerp** [comment]
Have you decided on how you are going to represent your data outside of topic models?

**Comment by richiebful** [comment]
We have a system of rhetorical tagging (you can see them [here](https://github.com/mtm80/russ-project#methodology)) to highlight what devices the speakers use
