### ISSUE TITLE
Project update 28 March

### ISSUE THREAD

**Issue by mtm80** [mtm80/russ-project#67]
For this week, Matt added rhetorical tags to one of the Zhirinovskii texts and over the following week, he will complete the rhetorical tags and expand web content.  Richard continued work with MALLET and TEI and added rhetorical tags to the Putin texts.  Ian continued work on the webpage design and will add rhetorical tags to the Grudinin texts.

**Comment by rmb165** [comment]
What is the status off your webpage so far? Have you considered incorporating SVG into your webpage to display any data? Something that my group is exploring now is what type of charts we will use to display our data.

**Comment by brucknerp** [comment]
Going along with @rmb165 's question, I'm excited to see how your use of topic models turned out, and was wondering if you guys have decided how you will display/visual/incorporate those models on your site.
