### ISSUE TITLE
Design concessions

### ISSUE THREAD

**Issue by richiebful** [mtm80/russ-project#94]
Originally, I wanted to integrate the reading views into to look and feel of the site. But since we have two parallel sites, one Russian, one English, and just one set of reading views, I decided that the complications from doing some sort of server-side solution to this problem wasn't worth the effort with two days left. Instead, I'm going to ask users to rely on their back button. 

I might put in the time later to resolve this peculiarity, but only after Friday.

**Comment by djbpitt** [comment]
@richiebful It’s reasonable not to resolve this by Friday, but SSIs do support conditionals, so you can include items in the menu or not depending on the URI of the the page that does the including. Here’s a snippet from the <http://repertorium.obdurodon.org> project:

```html
<!--#if expr='"$DOCUMENT_NAME" == "plectogram.php" || "$DOCUMENT_NAME" == "plectogram-dev-checkbox.php"' -->
        <span id="slider"><input id="slider1" type="range" value="1" min="0.1" max="2" step="0.01" /></span>
<!--#endif  -->
```
There may be a more elegant way to do this, but I had higher priorities when I wrote it, so I stopped looking once I found something that worked.
